package utb.ddbs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.3 2026-02-21T23:07:16.601-05:00
 * Generated source version: 3.0.3
 * 
 */
@WebService(targetNamespace = "http://ddbs.utb/", name = "PaymentProcessorService")
@XmlSeeAlso({ ObjectFactory.class })
public interface PaymentProcessorService {

	@WebMethod
	@RequestWrapper(localName = "makePayment", targetNamespace = "http://ddbs.utb/", className = "utb.ddbs.MakePayment")
	@ResponseWrapper(localName = "makePaymentResponse", targetNamespace = "http://ddbs.utb/", className = "utb.ddbs.MakePaymentResponse")
	@WebResult(name = "PaymentResponse", targetNamespace = "")
	public utb.ddbs.PaymentProcessingResponse makePayment(
			@WebParam(name = "PaymentRequest", targetNamespace = "") utb.ddbs.PaymentProcessingRequest paymentRequest);
}
