package utb.ddbs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.3
 * 2026-02-21T23:07:17.013-05:00
 * Generated source version: 3.0.3
 * 
 */
@WebServiceClient(name = "PaymentProcessorService", 
                  wsdlLocation = "file:/Users/elliottewideman/Desktop/Ksu_edu_webserviceLab/PaymentConsumer/src/main/resources/PaymentProcessor.wsdl",
                  targetNamespace = "http://ddbs.utb/") 
public class PaymentProcessorService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ddbs.utb/", "PaymentProcessorService");
    public final static QName PaymentProcessorServicePort = new QName("http://ddbs.utb/", "PaymentProcessorServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/elliottewideman/Desktop/Ksu_edu_webserviceLab/PaymentConsumer/src/main/resources/PaymentProcessor.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(PaymentProcessorService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/elliottewideman/Desktop/Ksu_edu_webserviceLab/PaymentConsumer/src/main/resources/PaymentProcessor.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public PaymentProcessorService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public PaymentProcessorService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PaymentProcessorService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentProcessorService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentProcessorService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public PaymentProcessorService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns PaymentProcessorService
     */
    @WebEndpoint(name = "PaymentProcessorServicePort")
    public PaymentProcessorService getPaymentProcessorServicePort() {
        return super.getPort(PaymentProcessorServicePort, PaymentProcessorService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PaymentProcessorService
     */
    @WebEndpoint(name = "PaymentProcessorServicePort")
    public PaymentProcessorService getPaymentProcessorServicePort(WebServiceFeature... features) {
        return super.getPort(PaymentProcessorServicePort, PaymentProcessorService.class, features);
    }

}
